

export enum Roles {

    CANDIDATE='CANDIDATE',
    EMPLOYEE = 'EMPLOYEE',

    LINE_MANAGER = 'MANAGER',
    DIRECT_MANAGER='DIRECT_MANAGER',

    Finance_Staff='Finance_Staff',
    Payroll_Specialist='Payroll_Specialist',
    PAYROLL_MANAGER='PAYROLL_MANAGER',

    LEGAL_AND_POLICY_ADMIN='LEGAL_AND_POLICY_ADMIN',

    HR_EMPLOYEE = 'HR EMPLOYEE',
    HR_MANAGER = 'HR_MANAGER',

    SYSTEM_ADMIN = 'SYSTEM_ADMIN'

}
