export enum PayrollRunStatus {
  PRE_RUN = 'PRE_RUN',
  INITIATED = 'INITIATED',
  DRAFT_GENERATED = 'DRAFT_GENERATED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  PUBLISHED = 'PUBLISHED',
  WAITING_MANAGER_APPROVAL = 'WAITING_MANAGER_APPROVAL',
  WAITING_FINANCE_APPROVAL = 'WAITING_FINANCE_APPROVAL',
  LOCKED = 'LOCKED',
  PAID = 'PAID',
  UNFROZEN = 'UNFROZEN',
}