export enum ApprovalActionType {
  PUBLISH = 'PUBLISH',
  MANAGER_APPROVE = 'MANAGER_APPROVE',
  MANAGER_REJECT = 'MANAGER_REJECT',
  FINANCE_APPROVE = 'FINANCE_APPROVE',
  FINANCE_REJECT = 'FINANCE_REJECT',
  LOCK = 'LOCK',
  UNFREEZE = 'UNFREEZE',
}